name: adp_assessment
version: 1.0.0
config-version: 2

profile: adp_assessment

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  adp_assessment:
    staging:
      +materialized: view
    marts:
      +materialized: table